import {
  HardDrive, FileText, Activity, Shield, Settings, FileDown, 
  UploadCloud, Search, User, ChevronDown, ChevronRight, LogOut, 
  Menu, X, Check, Folder, Save, Trash2, Zap, Download, Upload, 
  ShieldCheck, Plus, Key, Link, Clock, FileSignature, AlertTriangle,
  Play, RefreshCw, Lock, ArrowRight, ArrowUpDown, Calendar, FileJson,
  FileSpreadsheet, ExternalLink, Eye, EyeOff, Filter, XCircle, TrendingUp
} from 'lucide-react';

export const Icons = {
  HardDrive,
  FileText,
  Activity,
  Shield,
  Settings,
  FileDown,
  UploadCloud,
  Search,
  User,
  ChevronDown,
  ChevronRight,
  LogOut,
  Menu,
  X,
  Check,
  Folder,
  Save,
  Trash2,
  Zap,
  Download,
  Upload,
  ShieldCheck,
  Plus,
  Key,
  Link,
  Clock,
  FileSignature,
  AlertTriangle,
  Play,
  Refresh: RefreshCw, // Alias common names
  Lock,
  ArrowRight,
  ArrowUpDown,
  Calendar,
  FileJson,
  FileSpreadsheet,
  ExternalLink,
  Hide: EyeOff,
  Show: Eye,
  Filter,
  XCircle,
  TrendingUp,
  Archive: Folder // Fallback alias
};
